#!/usr/bin/env python
"""
python pwds [n chars - default 20]

Show the last n characters of `pwd`. The default is 20.
"""
import sys
import subprocess

if '-h' in sys.argv or '--help' in sys.argv:
    print(__doc__)
    sys.exit(1)

nchars = 20

if len(sys.argv) > 1:
    nchars = int(sys.argv[1])

mypwd = subprocess.check_output(["pwd"], shell=True)
print "..." + mypwd.strip()[-nchars:] + "/"
